# resolver: lts-9.6 # ghc-8.0.2

# resolver: lts-9.20  # ghc-8.0.2
# resolver: lts-11.12 # ghc-8.2.2
# resolver: lts-12.4  # ghc-8.4.3
resolver: lts-12.19 # ghc-8.4.4

# resolver: nightly-2018-11-23 # ghc-8.6.2

# "stack build" succeeds (warning-free) with all of the resolvers above.

packages:
- '.'
extra-deps:
  - nat-sized-numbers-0.1.0.0
flags: {}
extra-package-dbs: []
